
[package]
name = "w64-codegen-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote = "1.0.20"
syn = { version = "1.0.98", features = ["full"] }

w64-codegen-types = { path = "../types", features = ["macro"] }
